'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const core=require(path.resolve(__dirname,'../src/calculation-core.js'));
const keys='payroll payrollTax insurance vacation subcontract equipment scaffolding scaffoldLabor projectMaterials consumables nrk otherDirect indirectPayroll indirectTax indirectInsurance indirectVacation food housing bus car formwork ppe tickets permit medical vziz office warehouse internet waste safety accident it containers modularOffice transport otherIndirect'.split(' ');
const direct=new Set('payroll payrollTax insurance vacation subcontract equipment scaffolding scaffoldLabor projectMaterials consumables nrk otherDirect'.split(' '));
const manual=new Set('scaffolding otherDirect formwork it containers modularOffice transport'.split(' '));
const costDefs=keys.map(k=>[direct.has(k)?'direct':'indirect',k,k,manual.has(k)?'manual':'unit']);
const series=()=>Array(12).fill(0);
const drivers=Object.fromEntries('physicalVolume boqRate revenue otherRevenue materials directPeople indirectPeople equipmentHours nrkVolume payments advances advanceOffset factoring'.split(' ').map(k=>[k,series()]));
const parameters=Object.fromEntries(keys.map(k=>[k,{value:0,enabled:true,method:manual.has(k)?'manual':'unit',cash:true,vat:false,lag:0}]));
const version={year:2026,vatRate:20,vacationBasis:'monthly',drivers,parameters,workItems:[],manualCosts:{},manualPayments:{}};
const set=(key,value,props={})=>Object.assign(parameters[key],{value,...props});
drivers.physicalVolume[0]=2;drivers.boqRate[0]=50;drivers.otherRevenue[0]=10;drivers.directPeople[0]=2;drivers.equipmentHours[0]=3;drivers.materials[0]=40;drivers.payments[0]=120;drivers.advances[0]=24;drivers.advanceOffset[0]=12;
set('payroll',10);set('payrollTax',20);set('insurance',10);set('vacation',10);set('equipment',5,{vat:true,lag:1});set('projectMaterials',50,{vat:true});set('otherIndirect',10);parameters.otherIndirect.method='percentDirect';
const result=core.calculateModel(version,costDefs);
const close=(actual,expected,label)=>assert.ok(Math.abs(actual-expected)<1e-9,`${label}: ${actual} !== ${expected}`);
close(result.revenue[0],110,'BOQ volume × rate + other revenue');
close(result.rows.payroll[0],20,'direct payroll');
close(result.rows.payrollTax[0],5,'payroll gross-up');
close(result.rows.insurance[0],2.5,'insurance');
close(result.rows.vacation[0],2,'vacation reserve');
close(result.rows.equipment[0],15,'equipment hours × rate');
close(result.rows.projectMaterials[0],20,'materials base × percent');
close(result.rows.otherIndirect[0],2.95,'other indirect base');
close(result.direct[0],64.5,'direct costs');
close(result.indirect[0],2.95,'indirect costs');
close(result.costs[0],67.45,'all costs');
close(result.profit[0],42.55,'profit');
close(result.payments.equipment[0],0,'equipment payment lag');
close(result.payments.equipment[1],18,'equipment payment month 2 with VAT');
close(result.payments.projectMaterials[0],24,'materials payment with VAT');
close(result.inputVat[0],4,'input VAT');
close(result.vatPay[0],18,'VAT on payment + advance − offset − input');
close(result.inflow[0],132,'cash inflow');
close(result.operatingPayments[0],56.45,'cash expense');
close(result.ncf[0],57.55,'net cash flow');
close(result.cumulative[1],result.ncf[0]+result.ncf[1],'cumulative cash flow');
for(let m=0;m<12;m++){
 close(result.costs[m],result.direct[m]+result.indirect[m],`month ${m+1} expense reconciliation`);
 close(result.profit[m],result.revenue[m]-result.costs[m],`month ${m+1} profit reconciliation`);
 close(result.ncf[m],result.inflow[m]-result.operatingPayments[m]-result.vatPay[m],`month ${m+1} cash reconciliation`);
}
const manualVersion={...version,drivers:{...drivers,physicalVolume:series(),boqRate:series(),revenue:[75,...Array(11).fill(0)]},manualCosts:{...version.manualCosts,payroll:[30,...Array(11).fill(0)]},manualPayments:{...version.manualPayments,payroll:[7,...Array(11).fill(0)]},parameters:{...parameters,payroll:{...parameters.payroll,method:'manual'}}};
const manualResult=core.calculateModel(manualVersion,costDefs);
close(manualResult.revenue[0],85,'explicit manual revenue fallback');
close(manualResult.rows.payroll[0],30,'manual cost takes priority');
close(manualResult.payments.payroll[0],7,'manual payment takes priority');
const workVersion={...version,workItems:[{volumes:[4,...Array(11).fill(0)],rate:8}]};
close(core.calculateModel(workVersion,costDefs).revenue[0],42,'KSG work overrides BOQ fallback');
const yearEnd={...version,drivers:{...drivers,equipmentHours:[...Array(11).fill(0),2]},manualCosts:{},manualPayments:{}};
const yearEndResult=core.calculateModel(yearEnd,costDefs);
close(yearEndResult.deferred,12,'December equipment payment deferred beyond year');
close(yearEndResult.payments.equipment[11],0,'no phantom December equipment payment');
const annualReserve=core.calculateModel({...version,vacationBasis:'annual'},costDefs);
close(annualReserve.rows.vacation[0],2,'annual payroll reserve in January');
close(annualReserve.rows.vacation[1],2,'annual payroll reserve repeated monthly per current model');
console.log('ECONOMY REGRESSION: OK');
