'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../src/app.js'),'utf8');
const start=source.indexOf('function renderComparison(){'),end=source.indexOf('function changeParameter(e){',start);
assert(start>=0&&end>start);
const core=require('../src/calculation-core.js');
const series=(n=0)=>Array(12).fill(n),result=(revenue,cost)=>({revenue:series(revenue),costs:series(cost),direct:series(cost/2),indirect:series(cost/2),profit:series(revenue-cost),cumulative:series((revenue-cost)*12),rows:{payroll:series(100),equipment:series(50),indirectPayroll:series(80)}});
const base={id:'base',name:'База',year:2026,currency:'USD',fxRate:80,drivers:{directPeople:series(2),indirectPeople:series(1),equipmentHours:series(10)},workItems:[{stableKey:'work',name:'Монтаж',unit:'м',kq2:'KQ-01',rate:10,volumes:series(2)}]};
const current={...base,id:'current',name:'Текущая',year:2027,drivers:{directPeople:series(3),indirectPeople:series(2),equipmentHours:series(12)},workItems:[{stableKey:'work',name:'Монтаж',unit:'м',kq2:'KQ-01',rate:12,volumes:series(3)}]};
const elements={compareVersion:{value:'base',innerHTML:''},factorCurrentVersion:{textContent:''},factorTable:{innerHTML:''}};
const context={CalculationCore:core,COST_DEFS:[['direct','Заработная плата','payroll'],['direct','Строительная техника','equipment'],['indirect','Заработная плата','indirectPayroll']],state:{unit:1000000,results:result(20,10)},$:id=>elements[id],version:()=>current,contract:()=>({versions:[base,current]}),calcModel:()=>result(15,8),fxOf:v=>v.fxRate,rub:(n,v)=>n*v,sum:arr=>arr.reduce((a,b)=>a+Number(b||0),0),esc:s=>String(s).replaceAll('&','&amp;'),unitName:()=> 'млн RUB'};
vm.createContext(context);vm.runInContext(source.slice(start,end)+';this.renderComparison=renderComparison;',context);
context.renderComparison();
const html=elements.factorTable.innerHTML;
assert.match(html,/Текущая модель<\/th><th>Модель сравниваемая<\/th><th>Отклонение/);
assert.match(html,/Текущая · 2027/);
assert.match(html,/База · 2026/);
assert.match(html,/Ключевые физические объёмы/);
assert.match(html,/Прямой труд, расчётные чел.-ч/);
assert.match(html,/Средняя ставка прямого ФОТ/);
assert.match(html,/Объём · чел.-ч/);
assert.match(html,/Средняя ставка за маш.-ч/);
assert.match(html,/Косвенные/);
assert.match(html,/Финансовый результат/);
console.log('FACTOR BRIDGE VIEW: OK');
