'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../src/app.js'),'utf8');
const start=source.indexOf('function renderModelComments(){'),end=source.indexOf('function renderSummary(){',start);
assert(start>=0&&end>start);
const series=n=>[n,...Array(11).fill(0)];
const year={year:2026,currency:'RUB',fxRate:1,dataMode:'source_partial',revenueBasis:'ksg',drivers:{otherRevenue:series(5)},workSourceMeta:{ignoredRows:2,unmatchedRows:1,historicalCostSource:'исходной книги'}};
const result={scheduledRevenue:series(80),revenue:series(90),accepted:series(70),direct:series(30),indirect:series(20),costs:series(55),rows:{payroll:series(25),equipment:series(5),indirectPayroll:series(20)},advanceBalance:Array(12).fill(8),guaranteeBalance:Array(12).fill(3),profit:series(35),ncf:series(15),cumulative:Array(12).fill(-10),cashBridge:{accrualGap:-12,costTiming:-5,taxCash:3}};
const elements={summaryComments:{innerHTML:''},detailComments:{innerHTML:''}};
const context={periodVersions:()=>[{v:year,r:result}],resourceCoveragePreview:()=>({issues:['График персонала короче работ.']}),state:{unit:1},$:id=>elements[id],displayAmount:n=>n,displayCode:()=> 'RUB',unitName:()=> 'RUB',fmt:n=>String(n),fxOf:v=>v.fxRate,sum:arr=>arr.reduce((a,b)=>a+Number(b||0),0),COST_DEFS:[['direct','ФОТ','payroll'],['direct','Техника','equipment'],['indirect','ФОТ','indirectPayroll']],esc:s=>String(s).replaceAll('&','&amp;')};
vm.createContext(context);vm.runInContext(source.slice(start,end)+';this.renderModelComments=renderModelComments;',context);
context.renderModelComments();
const html=elements.summaryComments.innerHTML;
assert.equal(html,elements.detailComments.innerHTML);
for(const phrase of ['2 строк исключено','1 строк без оценки','корректировка 5','разница 10','неразнесённая сумма 5','незачтённый остаток','удержанный остаток','отклонение -20','График персонала'])assert.ok(html.includes(phrase),phrase);
assert.equal((html.match(/финансовый результат и CF:/g)||[]).length,1);
result.revenue=series(85);result.accepted=series(80);result.costs=series(50);result.ncf=series(35);result.cumulative=series(1);result.advanceBalance=series(0);result.guaranteeBalance=series(0);
context.renderModelComments();
const neutral=elements.summaryComments.innerHTML;
for(const phrase of ['корректировка','разница 10','неразнесённая сумма','незачтённый остаток','удержанный остаток','финансовый результат и CF:'])assert.ok(!neutral.includes(phrase),phrase);
console.log('MODEL COMMENTS: OK');
